---
Name: silverstripe-ai-routes
After: '#rootroutes'
---
SilverStripe\Control\Director:
  rules:
    'api/ai/agent//$Action': 'Hudhaifas\AI\Controller\AgentController'
    'api/ai/content//$Action/$ID/$Name': 'Hudhaifas\AI\Controller\ContentController'
